#! /usr/bin/env python

from tfnet import *
from tensorflow import flags

flags.DEFINE_string("testset", "./test/", "path to testing directory")
flags.DEFINE_string("binary", "./bin/", "path to .weights directory")
flags.DEFINE_string("config", "./configs/", "path to .cfg directory")
flags.DEFINE_string("dataset", "../pascal/VOCdevkit/IMG/", "path to dataset directory")
flags.DEFINE_string("annotation", "../pascal/VOCdevkit/ANN/", "path to annotation directory")
flags.DEFINE_float("threshold", 0.1, "detection threshold")
flags.DEFINE_string("model", "", "configuration of choice")
flags.DEFINE_boolean("verbalise", True, "say out loud while building graph")
flags.DEFINE_boolean("train", False, "training mode or not?")
flags.DEFINE_string("load", "", "How to initialize the net? Either from .weights or a checkpoint, or even from scratch")
flags.DEFINE_boolean("savepb", False, "save net and weight to a .pb file")
flags.DEFINE_float("gpu", 0.0, "How much gpu (from 0.0 to 1.0)")
flags.DEFINE_float("lr", 1e-5, "Learning rate")
flags.DEFINE_integer("keep",20,"Number of most recent training results to save")
flags.DEFINE_integer("batch", 12, "Batch size")
flags.DEFINE_integer("epoch", 1000, "Number of epoch")
flags.DEFINE_integer("save", 2000, "Save checkpoint every ? training examples")
FLAGS = flags.FLAGS

# make sure all necessary dirs exist
def get_dir(dirs):
	for d in dirs:
		this = os.path.abspath(os.path.join(os.path.curdir, d))
		if not os.path.exists(this): os.makedirs(this)
get_dir([FLAGS.testset, FLAGS.binary, 'results', 'backup'])

# fix FLAGS.load to appropriate type
try: FLAGS.load = int(FLAGS.load)
except: pass

# now get to the real work
darknet = Darknet(FLAGS)
darknet.load_weights()

print ('\nCompiling net & fill in parameters...')
start = time.time()
if FLAGS.gpu <= 0.: 
	with tf.device('cpu:0'): tfnet = TFNet(darknet, FLAGS)
else: tfnet = TFNet(darknet, FLAGS)
print ('Finished in {}s\n'.format(time.time() - start))

if FLAGS.train:
	print 'Enter training ...';	tfnet.train()
	if not FLAGS.savepb: exit('Training finished')

if FLAGS.savepb:
	print 'Rebuild a constant version ...'
	tfnet.savepb(); exit('Done')

tfnet.predict()